# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  LLink1_2_LLink2:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  Link1_2_Link2:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  Link2_2_Link3:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  Link3_2_Link4:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  Link4_2_Link5:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0
  RLink1_2_RLink2:
    has_velocity_limits: true
    max_velocity: 1.571
    has_acceleration_limits: false
    max_acceleration: 0